project:
  type: website
  output-dir: docs

execute:
  engine: jupyter

website:
  title: "Gapminder Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy & GDP
      - href: life-population.qmd
        text: Life Expectancy & Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme: flatly
    toc: true
    embed-resources: true
    css: custom.css